### ISSUE TITLE
Feature: Multiple Minter/Token Addresses

### ISSUE THREAD

**Issue by djrobzilla** [stepwn/LoopPress#1]
Add the ability to specify multiple Token and/or Minter addresses. 

Bonus: allow AND and OR operators to be specified, so that you could, for example: 

- Own either of two or more specific NFTs to gain access
- Own all of two or more specific NFTs to gain access
- Own either of two or more NFTs from a particular minter to gain access
- Own all of two or more NFTs from a particular minter to gain access

**Comment by stepwn** [comment]
Multiples were just added. Use multiple token, minter, or nft_id parameters by separating them with a comma. 

[looppress_required nft_id="nftid1,nftid2,nftid3"]
